server.port=8080
spring.application.name=slot-machine-backend

# Configurações de Cookie de Sessão para Produção Cross-Site (Vercel + Render)
server.servlet.session.cookie.same-site=none
server.servlet.session.cookie.secure=true
